package example.jeevankumar.stockprice;

import android.app.Activity;
import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;

import java.text.DecimalFormat;

public class Stockop extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_stockop);
        double intrin;
        double one;
        TextView t1=(TextView) findViewById(R.id.textView8);
        TextView t2=(TextView) findViewById(R.id.textView7);
        Intent i=getIntent();
        intrin=i.getExtras().getDouble("intrin");
        one=i.getExtras().getDouble("one");
        t1.setText("If You Invest $100k, $"+new DecimalFormat("##.##").format(one)+" is the money Generated by the business this year.");
        t2.setText("The intrinsic value of the stock is "+new DecimalFormat("##.##").format(intrin));
    }

    public void onlast(View view){
        Intent intent=new Intent(".Stockone");
        startActivity(intent);
    }
}
